# Generated by Django 3.2.25 on 2024-08-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=7, verbose_name='Código SICON')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(help_text='Preenchido automaticamente, não editar.', max_length=100, unique=True, verbose_name='Identificador')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Descrição')),
                ('unid', models.CharField(max_length=100, verbose_name='Unidades')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['name'],
            },
        ),
    ]
