# Generated by Django 3.2.25 on 2024-08-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
        migrations.RemoveField(
            model_name='material',
            name='slug',
        ),
    ]
